<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>performance_lab_stub</RootNamespace>
    <AssemblyName>performance_lab_stub</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\sorting\sorting.csproj" />
    <ProjectReference Include="..\searching\searching.csproj" />
    <ProjectReference Include="..\binary_searching\binary_searching.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
