<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>test_rational</RootNamespace>
    <AssemblyName>test_rational</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\rational_nunit\rational_nunit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
