<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>cmdline_to_file</RootNamespace>
    <AssemblyName>cmdline_to_file</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
    <Compile Remove="cmdline_to_file_tests.cs" />
  </ItemGroup>
</Project>
