<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>dict_lab_stub</RootNamespace>
    <AssemblyName>dict_lab_stub</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\fio\fio.csproj" />
    <ProjectReference Include="..\ui\ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="help_not_defaults.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="help_not_responses.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="help_not_responses2.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
