<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>fio_usage</RootNamespace>
    <AssemblyName>fio_usage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\fio\fio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="sample.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
