<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>g_c_d_remainder_loop</RootNamespace>
    <AssemblyName>g_c_d_remainder_loop</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ui\ui.csproj" />
  </ItemGroup>
</Project>
