<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>music_nunit</RootNamespace>
    <AssemblyName>music_nunit</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\rational_nunit\rational_nunit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
    <Compile Remove="notation_tests.cs" />
  </ItemGroup>
</Project>
