<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>binary_searching</RootNamespace>
    <AssemblyName>binary_searching</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ui\ui.csproj" />
    <ProjectReference Include="..\searching\searching.csproj" />
    <ProjectReference Include="..\sorting\sorting.csproj" />
  </ItemGroup>
</Project>
