<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>g_c_d_basic</RootNamespace>
    <AssemblyName>g_c_d_basic</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ui\ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
    <Compile Remove="g_c_d_basic_tests.cs" />
  </ItemGroup>
</Project>
