<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>cs_project1</RootNamespace>
    <AssemblyName>cs_project1</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ui\ui.csproj" />
    <ProjectReference Include="..\fio\fio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="place_data.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
