<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>fake_help_verbose</RootNamespace>
    <AssemblyName>fake_help_verbose</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ui\ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
