<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>sum_to_n_long_bad</RootNamespace>
    <AssemblyName>sum_to_n_long_bad</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ui\ui.csproj" />
  </ItemGroup>
</Project>
