<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>sum_file</RootNamespace>
    <AssemblyName>sum_file</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ui\ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="numbers.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
