<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>word_search_puzzle</RootNamespace>
    <AssemblyName>word_search_puzzle</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
