<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>rational_nunit</RootNamespace>
    <AssemblyName>rational_nunit</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs" />
    <Compile Remove="rational_unit_tests.cs" />
  </ItemGroup>
</Project>
